name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - 'TODO.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - 'TODO.md'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Cloner le dépôt
    - name: Checkout repository
      uses: actions/checkout@v4

    # Étape 2 : Set up QEMU pour le multi-arch
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    # Étape 3 : Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        install: true
        use: true

    # Étape 4 : Connexion à Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Étape 5 : Construire et pousser l'image Docker avec cache optimisé
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        push: true
        tags: tiritibambix/imaguick:latest
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max
        provenance: false

    # Étape 6 : Mettre à jour la description de Docker Hub
    - name: Update Docker Hub description
      uses: peter-evans/dockerhub-description@v4
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: tiritibambix/imaguick
        readme-filepath: ./README.md
        short-description: "ImaGUIck - A GUI tool for image processing and batch operations"

    # Étape 7 : Logout de Docker Hub proprement
    - name: Logout from Docker Hub
      if: always()  # Assure que le logout s'exécute même en cas d'erreur
      run: docker logout