name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - 'TODO.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - 'TODO.md'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Activer les fonctionnalités expérimentales de Docker si nécessaire
    - name: Enable experimental features
      run: echo "DOCKER_CLI_EXPERIMENTAL=enabled" >> $GITHUB_ENV

    # Set up QEMU pour build multi-architecture
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build et push avec cache optimisé
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        push: true
        tags: tiritibambix/imaguick:latest
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha, type=registry
        cache-to: type=gha, type=registry,mode=max
        provenance: false

    # Mettre à jour la description de Docker Hub
    - name: Update Docker Hub description
      uses: peter-evans/dockerhub-description@v4
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: tiritibambix/imaguick
        readme-filepath: ./README.md
        short-description: "ImaGUIck - A GUI tool for image processing and batch operations"

    # Logout de Docker Hub
    - name: Logout from Docker Hub
      run: docker logout
